### ISSUE TITLE
todo for friday

### ISSUE THREAD

**Issue by konstantinosKokos** [gtziafas/Type-Enhanced-Language-Modeling#4]
- [x] sigsoftmax for MLM
- [x] uncertainty type prediction
- [x] probabilistic embedder
- [x] mixed embeddings gate word predictions
